server:
  port: 8082

spring:

  datasource:
    url: jdbc:postgresql://localhost:5434/ead-course
    username: postgres
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creaction: true
    properties:
      hibernate:
        show_sql: true

  output:
    ansi:
      enabled: always

logging:
  level:
    root: info
    org.springframework.web: debug
    org.hibernate: info
    com.ead: trace

ead:
  api:
    url:
      authuser: 'http://localhost:8087'