spring:
  application:
    name: ead-course-service
  config:
    import: 'configserver:'
  cloud:
    config:
      discovery:
        serviceId: ead-config-server
#server:
#  port: 8082
#  servlet:
#    context-path: '/ead-course/'
#
#  datasource:
#    url: jdbc:postgresql://localhost:5434/ead-course
#    username: postgres
#    password: 123456
#  jpa:
#    hibernate:
#      ddl-auto: update
#      dialect: org.hibernate.dialect.PostgreSQLDialect
#      jdbc:
#        lob.non-contextual-creaction: true
#    properties:
#      hibernate:
#        show_sql: true
#  output:
#    ansi:
#      enabled: always
#  rabbitmq:
#    addresses: amqps://uwkbdeas:0QhCNUCvbbiSwuXmw4buwvkd-cHtcpGC@shrimp.rmq.cloudamqp.com/uwkbdeas
#
#logging:
#  level:
#    root: info
#    org.springframework.web: debug
#    org.hibernate: info
#    com.ead: trace
#
#ead:
#  api:
#    url:
#      authuser: 'http://ead-authuser-service/ead-authuser'
#  broker:
#    exchange:
#      userEventExchange: ead.userevent
#    queue:
#      userEventQueue:
#        name: ead.userevent.ms.course
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: 'http://localhost:8761/eureka'
#  instance:
#    hostname: localhost